package VO;

import java.util.Date;

public class Recruit_ReplyVO {
	private int RECRUIT_REPLY_NO;
	private String RECRUIT_REPLY_CONTENT;
	private String M_ID;
	private int REC_NO;
	private int PARENT_REC_REPLY_NO;
	private Date RECRUIT_REPLY_CREATE_DATE;
	private Date RECRUIT_REPLY_UPDATE_DATE;
	private Date RECRUIT_REPLY_DELETE_DATE;
	
	
	
	public Recruit_ReplyVO(String rECRUIT_REPLY_CONTENT, int rEC_NO, int pARENT_REC_REPLY_NO) {
		super();
		RECRUIT_REPLY_CONTENT = rECRUIT_REPLY_CONTENT;
		REC_NO = rEC_NO;
		PARENT_REC_REPLY_NO = pARENT_REC_REPLY_NO;
	}
	public Recruit_ReplyVO(int rEC_NO) {
		REC_NO = rEC_NO;
	}
	public Recruit_ReplyVO() {
		super();
	}
	public Recruit_ReplyVO(int rECRUIT_REPLY_NO, String rECRUIT_REPLY_CONTENT, String m_ID, int rEC_NO,
			int pARENT_REC_REPLY_NO, Date rECRUIT_REPLY_CREATE_DATE, Date rECRUIT_REPLY_UPDATE_DATE,
			Date rECRUIT_REPLY_DELETE_DATE) {
		super();
		RECRUIT_REPLY_NO = rECRUIT_REPLY_NO;
		RECRUIT_REPLY_CONTENT = rECRUIT_REPLY_CONTENT;
		M_ID = m_ID;
		REC_NO = rEC_NO;
		PARENT_REC_REPLY_NO = pARENT_REC_REPLY_NO;
		RECRUIT_REPLY_CREATE_DATE = rECRUIT_REPLY_CREATE_DATE;
		RECRUIT_REPLY_UPDATE_DATE = rECRUIT_REPLY_UPDATE_DATE;
		RECRUIT_REPLY_DELETE_DATE = rECRUIT_REPLY_DELETE_DATE;
	}
	public int getRECRUIT_REPLY_NO() {
		return RECRUIT_REPLY_NO;
	}
	public void setRECRUIT_REPLY_NO(int rECRUIT_REPLY_NO) {
		RECRUIT_REPLY_NO = rECRUIT_REPLY_NO;
	}
	public String getRECRUIT_REPLY_CONTENT() {
		return RECRUIT_REPLY_CONTENT;
	}
	public void setRECRUIT_REPLY_CONTENT(String rECRUIT_REPLY_CONTENT) {
		RECRUIT_REPLY_CONTENT = rECRUIT_REPLY_CONTENT;
	}
	public String getM_ID() {
		return M_ID;
	}
	public void setM_ID(String m_ID) {
		M_ID = m_ID;
	}
	public int getREC_NO() {
		return REC_NO;
	}
	public void setREC_NO(int rEC_NO) {
		REC_NO = rEC_NO;
	}
	public int getPARENT_REC_REPLY_NO() {
		return PARENT_REC_REPLY_NO;
	}
	public void setPARENT_REC_REPLY_NO(int pARENT_REC_REPLY_NO) {
		PARENT_REC_REPLY_NO = pARENT_REC_REPLY_NO;
	}
	public Date getRECRUIT_REPLY_CREATE_DATE() {
		return RECRUIT_REPLY_CREATE_DATE;
	}
	public void setRECRUIT_REPLY_CREATE_DATE(Date rECRUIT_REPLY_CREATE_DATE) {
		RECRUIT_REPLY_CREATE_DATE = rECRUIT_REPLY_CREATE_DATE;
	}
	public Date getRECRUIT_REPLY_UPDATE_DATE() {
		return RECRUIT_REPLY_UPDATE_DATE;
	}
	public void setRECRUIT_REPLY_UPDATE_DATE(Date rECRUIT_REPLY_UPDATE_DATE) {
		RECRUIT_REPLY_UPDATE_DATE = rECRUIT_REPLY_UPDATE_DATE;
	}
	public Date getRECRUIT_REPLY_DELETE_DATE() {
		return RECRUIT_REPLY_DELETE_DATE;
	}
	public void setRECRUIT_REPLY_DELETE_DATE(Date rECRUIT_REPLY_DELETE_DATE) {
		RECRUIT_REPLY_DELETE_DATE = rECRUIT_REPLY_DELETE_DATE;
	}
	@Override
	public String toString() {
		return "Recruit_ReplyVO [RECRUIT_REPLY_NO=" + RECRUIT_REPLY_NO + ", RECRUIT_REPLY_CONTENT="
				+ RECRUIT_REPLY_CONTENT + ", M_ID=" + M_ID + ", REC_NO=" + REC_NO + ", PARENT_REC_REPLY_NO="
				+ PARENT_REC_REPLY_NO + ", RECRUIT_REPLY_CREATE_DATE=" + RECRUIT_REPLY_CREATE_DATE
				+ ", RECRUIT_REPLY_UPDATE_DATE=" + RECRUIT_REPLY_UPDATE_DATE + ", RECRUIT_REPLY_DELETE_DATE="
				+ RECRUIT_REPLY_DELETE_DATE + "]";
	}
}
